name: Continuous Integration
on: [push]
jobs:
  test-linux-x64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Bootstrap
      run: |
        sudo apt-get update -y
        sudo apt-get install -y ccache clang gcc-arm-none-eabi ninja-build
        wget https://github.com/mozilla/grcov/releases/download/v0.8.7/grcov-x86_64-unknown-linux-gnu.tar.bz2
        tar xjf grcov-x86_64-unknown-linux-gnu.tar.bz2
        echo "embeddedPrefix = /usr/bin/arm-none-eabi-" > local.ninja
    - name: Build
      run: ninja
    - name: Test
      run: output/host/bin/ResolVBusTest
    - name: Coverage
      run: |
        ./grcov output/host -s . -t lcov --ignore-not-existing -o output/host/coverage.lcov
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true
        files: ./output/host/coverage.lcov
        flags: unittests
        name: codecov-umbrella
        verbose: true

  # test-macos-x64:
  #   runs-on: macos-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Bootstrap
  #     run: |
  #       brew update
  #       brew install ccache ninja
  #       echo "" > local.ninja
  #   - name: Build
  #     run: ninja hostTests
  #   - name: Test
  #     run: output/host/bin/ResolVBusTest
